# bookmanagement schema

# --- !Ups
SET SESSION FOREIGN_KEY_CHECKS=0;

/* Create Tables */
CREATE TABLE BOOK
(
    ID INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    ACQUISITION_DATE DATE NOT NULL COMMENT '購入日',
    RELEASE_DATE DATE NOT NULL COMMENT '発売日',
    STOK INT DEFAULT 0 NOT NULL COMMENT '在庫',
    URL TEXT NOT NULL COMMENT 'URL',
    PHOTOFILENAME VARCHAR(1024) NOT NULL COMMENT '画像ファイル名',
    PRIMARY KEY (ID)
) COMMENT = '書籍';

CREATE TABLE RENTAL
(
    BOOK_ID INT NOT NULL COMMENT '貸出書籍',
    USER_ID INT NOT NULL COMMENT '貸出ユーザID',
    RENTAL_DATE DATE NOT NULL COMMENT 'RENTAL日付',
    PRIMARY KEY (BOOK_ID, USER_ID)
) COMMENT = 'rental';

CREATE TABLE USERMASTER
(
    ID INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    PRIMARY KEY (ID)
) COMMENT = 'ユーザマスター';

/* Create Foreign Keys */
ALTER TABLE RENTAL
    ADD CONSTRAINT RENTAL_IBFK_1 FOREIGN KEY (BOOK_ID)
    REFERENCES BOOK (ID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
;
ALTER TABLE RENTAL
    ADD FOREIGN KEY (USER_ID)
    REFERENCES USERMASTER (ID)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
;


# --- !Downs
/* Drop Tables */
DROP TABLE IF EXISTS RENTAL;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS USERMASTER;
